[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps"]

[phases.build]
cmds = ["npx prisma generate", "rm -rf .next/cache", "npm run build", "echo BUILD_ID=$(date +%s)"]

[start]
cmd = "npm run start"
